this is my first line in exceptions
{'id':1,'name'':'python','adhar':'2134wqrewr32'}